### ISSUE TITLE
Duplicating check_list check_patron permission

### ISSUE THREAD

**Issue by kidclamp** [bywatersolutions/koha-plugin-batch-permissions-modifier#2]
The plugin is inserting multiple instance sof check_list and check_patron permissions into the user_permissions table (IGNORE is NOT working)

This is a blocker, it is creating millions of rows

**Comment by fridobox** [comment]
Is this still valid ?

**Comment by kylemhall** [comment]
Seems like it should be based on https://github.com/bywatersolutions/koha-plugin-batch-permissions-modifier/blob/81cf5eed1da1da6894be08d63b8623aa5e2c7772/Koha/Plugin/Com/ByWaterSolutions/BatchPermissionsModifier.pm#L307

What do you think @kidclamp

**Comment by kidclamp** [comment]
I think the Jan 8 2019 commits fixed this:
https://github.com/bywatersolutions/koha-plugin-batch-permissions-modifier/commit/e0713e7d1fdf8910f4d16d0b6cc987355b6ca88a

**Comment by kylemhall** [comment]
👍
