### ISSUE TITLE
Show permissions when mapped to list

### ISSUE THREAD

**Issue by CrispyBran** [bywatersolutions/koha-plugin-batch-permissions-modifier#5]
It would be preferred if the permissions were showing under the warning about being mapped, and just disabled from being changed.

**Comment by CrispyBran** [comment]
Another thought might be to show permissions, but only grey out the ones controlled by the list.  That way, if you need to give a specific person one extra permission, you can.

**Comment by will1410** [comment]
I uploaded a patch that should resolve this issue if accepted.
